Repository jflex-de/jflex, pull requests merged in 2018-09, with the labels that each got.

#305 Minor: Rename jflextest.Main to jflextest.Tester
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/JFlexTestsuiteMojo.java
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/TestCase.java
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/Tester.java
Labels: code health

#325 Use Maven wrapper in deploy script
  mvn-deploy.sh
Labels: task

#331 Fix typo when calling deploy-source-code.sh
  .travis.yml
  scripts/deploy-source-code.sh
Labels: bug

#323 Minor: Udpate Windows batch script
  jflex/bin/jflex.bat
Labels: bug

#337 adjust whitespace for character reporting
  jflex/src/main/java/jflex/Emitter.java
Labels: bug

#332 Update travis.yml to deploy only once
  .travis.yml
  scripts/deploy-source-code.sh
  scripts/mvn-aggregate-srcs.sh
  scripts/mvn-site.sh
Labels: code health

#344 chmod u+x ./scripts/mvn-aggregate-srcs.sh
  scripts/mvn-aggregate-srcs.sh
Labels: bug

#348 Deploy script must do git config to set Travis identity
  scripts/deploy-source-code.sh
Labels: bug

#349 Use ssh to clone the repository
  scripts/deploy-source-code.sh
Labels: bug

#351 Use git clone on https with existing GITHUB_TOKEN
  scripts/deploy-source-code.sh
Labels: bug

#356 Don't commit on a clean working tree for aggregated-java-sources
  scripts/deploy-source-code.sh
Labels: bug

#368 expl zeroreader: diff ignoring different EOL
  jflex/examples/zero-reader/Makefile
Labels: bug

#366 jflex.bat: JFLEX vars definable in cmd shell
  jflex/bin/jflex.bat
Labels: bug

#365 Use truth assertions in tests.
  jflex-maven-plugin/pom.xml
  jflex-maven-plugin/src/test/java/de/jflex/plugin/maven/ClassInfoTest.java
  jflex-maven-plugin/src/test/java/de/jflex/plugin/maven/JFlexMojoTest.java
  jflex/examples/cup-maven/pom.xml
  jflex/examples/cup-maven/src/test/java/LexerTest.java
  jflex/examples/simple-maven/pom.xml
  jflex/examples/simple-maven/src/test/java/YylexTest.java
  jflex/examples/standalone-maven/pom.xml
  jflex/examples/standalone-maven/src/test/java/de/jflex/example/standalone/SubstTest.java
Labels: code health

#363 Add openjdk9 in the build matrix
  .travis.yml
  cup-maven-plugin/pom.xml
  cup/pom.xml
  jflex/examples/cup-maven/pom.xml
  jflex/examples/pom.xml
  jflex/examples/simple-maven/pom.xml
  jflex/examples/standalone-maven/pom.xml
  pom.xml
  testsuite/jflex-testsuite-maven-plugin/pom.xml
Labels: code health

#378 Fix git commit --message for aggregate-java-sources
  scripts/deploy-source-code.sh
Labels: bug

#370 doc: Bump version of the jflex-maven-plugin to 1.7.1-SNPASHOT
  docs/md/maven-plugin.md
Labels: documentation

#382 Upgrade maven wrapper to v0.4.2
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: task

#377 Remove openjdk7 from the build matrix
  .travis.yml
Labels: code health

#381 Use ${project.version} in documentation
  docs/Makefile
  docs/md/maven-plugin.md
Labels: documentation

#371 Indicate the lex source file in the header of the java source
  jflex-maven-plugin/src/main/java/de/jflex/plugin/maven/JFlexMojo.java
  jflex/src/main/java/jflex/Emitter.java
  jflex/src/main/java/jflex/Options.java
  jflex/src/main/java/jflex/io/FileUtil.java
  jflex/src/test/java/jflex/io/FileUtilTest.java
Labels: enhancement

#374 Add a TEST_SUITE to run google-java-format
  .travis.yml
  pom.xml
  scripts/run-tests.sh
  scripts/test-java-format.sh
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflextest/JFlexTestsuiteMojo.java
Labels: code health

#387 Replace CONTRIBUTING.md by a wiki page
  CONTRIBUTING.md
  README.md
Labels: documentation

#386 Add CUP license in jflex-full.jar
  cup/cup_runtime/src/main/resources/LICENSE_CUP
  jflex/src/main/resources/LICENSE_JFLEX
  scripts/deploy-source-code.sh
  scripts/logger.sh
Labels: task

#392 Fix typo in after_success travis script
  .travis.yml
Labels: bug

#395 Add Bazel job in Travis
  .travis.bazelrc
  .travis.yml
  jflex/.gitignore
  jflex/examples/.gitignore
  jflex/examples/BUILD
  jflex/examples/WORKSPACE
  scripts/bazel.sh
  scripts/run-tests.sh
Labels: enhancement, task
