Repository jflex-de/jflex, pull requests merged in 2019-12, with the labels that each got.

#641 Method can be static
  jflex/src/main/java/jflex/generator/Emitter.java
  jflex/src/main/java/jflex/generator/LexGenerator.java
  jflex/src/main/java/jflex/generator/PackEmitter.java
Labels: code health

#645 Update Maven site
  docs/md/maven-plugin.md
  jflex-maven-plugin/pom.xml
  jflex-maven-plugin/src/site/site.xml
  pom.xml
Labels: documentation

#642 Bazelify testcase/eofclose
  java/jflex/util/scanner/ScannerFactory.java
  javatests/jflex/testcase/eofclose/BUILD
  javatests/jflex/testcase/eofclose/EofCloseTest.java
  javatests/jflex/testcase/eofclose/eofclose.flex
  javatests/jflex/testcase/eofclose/eofnoclose.flex
  testsuite/testcases/src/test/cases/eofclose/README.md
  testsuite/testcases/src/test/cases/eofclose2/README.md
Labels: testing

#644 Expose `yyatEOF()` in generated scanner API
  docs/md/lex-specs.md
  java/jflex/migration/TestCase.java.vm
  javatests/jflex/testcase/eof_min/EofminGoldenTest.java
  javatests/jflex/testcase/fixed_look/FixedlookGoldenTest.java
  javatests/jflex/testcase/fixed_look/fixedlook-0.output
  javatests/jflex/testcase/fixed_look/fixedlook-1.output
  javatests/jflex/testcase/fixed_look/fixedlook-2.output
  javatests/jflex/testcase/fixed_look/fixedlook-3.output
  jflex/src/main/jflex/skeleton.nested
  jflex/src/main/resources/jflex/skeleton.default
Labels: enhancement

#647 Make LargeInputTest run much faster by faking the scanner position
  javatests/jflex/testcase/large_input/BUILD
  javatests/jflex/testcase/large_input/LargeInputTest.java
  javatests/jflex/testcase/large_input/large_input.flex
Labels: testing

#650 normalise char class order before NFA construction
  jflex/src/main/cup/LexParse.cup
  jflex/src/main/java/jflex/core/CharClasses.java
  jflex/src/main/java/jflex/core/IntCharSet.java
  testsuite/testcases/src/test/cases/bol/bol-flex.output
  testsuite/testcases/src/test/cases/ccl-esc/ccl-flex.output
  testsuite/testcases/src/test/cases/ccl-pre/ccl3-flex.output
Labels: code health

#652 decouple CharClasses from AbstractLexScan
  jflex/src/main/java/jflex/core/CharClasses.java
Labels: code health

#648 Change depth of chapters in manual
  docs/docs.bzl
  docs/md/encodings.md
  docs/md/generated-class.md
  docs/md/lex-specs.md
Labels: documentation

#655 Upgrade to Bazel 1.2.1
  .cirrus.yml
Labels: task

#656 Minor code changes
  jflex/src/main/java/jflex/chars/Interval.java
  jflex/src/main/java/jflex/core/CharClasses.java
  jflex/src/main/java/jflex/core/IntCharSet.java
  jflex/src/main/java/jflex/core/Macros.java
  jflex/src/main/java/jflex/core/NFA.java
  jflex/src/main/java/jflex/core/RegExp.java
  jflex/src/main/java/jflex/core/RegExp1.java
  jflex/src/main/java/jflex/core/RegExp2.java
  jflex/src/main/java/jflex/core/RegExps.java
  jflex/src/main/java/jflex/exceptions/CharClassException.java
  jflex/src/main/java/jflex/exceptions/MacroException.java
  jflex/src/test/java/jflex/core/BUILD
  jflex/src/test/java/jflex/core/IntCharSetTest.java
Labels: code health

#659 Add junit_artifacts to Cirrus CI
  .cirrus.yml
Labels: testing

#660 Use Truth for all test assertions
  .bazelrc
  jflex/src/test/java/jflex/anttask/JFlexTaskTest.java
  jflex/src/test/java/jflex/core/BUILD
  jflex/src/test/java/jflex/core/CharClassesTest.java
  jflex/src/test/java/jflex/core/IntCharSetTest.java
  jflex/src/test/java/jflex/core/RegExpTests.java
  jflex/src/test/java/jflex/core/SkeletonTest.java
  jflex/src/test/java/jflex/generator/BUILD
  jflex/src/test/java/jflex/generator/EmitterTest.java
  jflex/src/test/java/jflex/generator/PackEmitterTest.java
  jflex/src/test/java/jflex/unicode/BUILD
  jflex/src/test/java/jflex/unicode/UnicodePropertiesTest.java
Labels: testing

#663 Quickcheck
  WORKSPACE
  jflex/pom.xml
  jflex/src/main/java/jflex/core/IntCharSet.java
  jflex/src/test/java/jflex/core/BUILD
  jflex/src/test/java/jflex/core/IntCharSetGen.java
  jflex/src/test/java/jflex/core/IntCharSetQuickcheck.java
  third_party/com/google/auto_value/BUILD
  third_party/com/pholser/quickcheck/BUILD
  third_party/deps.bzl
  third_party/maven_install.json
Labels: testing

#666 Don't allow instantiation of Unicode_x_y.java
  jflex-unicode-maven-plugin/src/main/java/jflex/maven/plugin/unicode/UnicodeVersion.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_10_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_11_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_12_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_12_1.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_1_1.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_2_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_2_1.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_3_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_3_1.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_3_2.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_4_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_4_1.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_5_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_5_1.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_5_2.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_6_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_6_1.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_6_2.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_6_3.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_7_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_8_0.java
  jflex/src/main/java/jflex/core/unicode/data/Unicode_9_0.java
Labels: code health

#667 remove the MainFrame.stop button that called deprecated Thread.stop()
  jflex/src/main/java/jflex/gui/MainFrame.java
Labels: code health

#668 address a few more error-prone warnings
  jflex/src/main/java/jflex/anttask/JFlexTask.java
  jflex/src/main/java/jflex/core/Macros.java
  jflex/src/main/java/jflex/core/Options.java
  jflex/src/main/java/jflex/core/SemCheck.java
  jflex/src/main/java/jflex/core/unicode/UnicodeProperties.java
  jflex/src/main/java/jflex/gui/MainFrame.java
Labels: code health

#669 use RegExpException
  jflex/src/main/java/jflex/core/SemCheck.java
Labels: code health

#670 generated getTokenName(int) (%cupdebug) can be static
  jflex/src/main/java/jflex/generator/Emitter.java
Labels: code health

#671 makeCCL can no longer throw CharClassException
  jflex/src/main/cup/LexParse.cup
Labels: code health

#675 Minor src/test/java improvements
  jflex/src/main/java/jflex/core/IntCharSet.java
  jflex/src/main/java/jflex/core/RegExp.java
  jflex/src/main/java/jflex/generator/Emitter.java
  jflex/src/test/java/jflex/core/BUILD
  jflex/src/test/java/jflex/core/CharClassesTest.java
  jflex/src/test/java/jflex/core/IntCharSetTest.java
  jflex/src/test/java/jflex/core/RegExpTest.java
Labels: testing

#676 Minor: Simplify code
  jflex/src/main/java/jflex/core/RegExp.java
Labels: code health

#680 more IntCharSet quickcheck
  jflex/src/main/java/jflex/core/unicode/CharClasses.java
  jflex/src/test/java/jflex/chars/BUILD
  jflex/src/test/java/jflex/chars/IntervalGen.java
  jflex/src/test/java/jflex/core/unicode/BUILD
  jflex/src/test/java/jflex/core/unicode/IntCharSetGen.java
  jflex/src/test/java/jflex/core/unicode/IntCharSetQuickcheck.java
Labels: testing

#677 Bazelify testcase/line-cont
  java/jflex/migration/Migrator.java
  java/jflex/testing/diff/DiffOutputStream.java
  java/jflex/testing/testsuite/JFlexTestRunner.java
  java/jflex/testing/testsuite/annotations/TestSpec.java
  javatests/jflex/testcase/line_cont/BUILD
  javatests/jflex/testcase/line_cont/LineTest.java
  javatests/jflex/testcase/line_cont/line-flex.syserr
  javatests/jflex/testcase/line_cont/line-flex.sysout
  javatests/jflex/testcase/line_cont/line.flex
  testsuite/testcases/src/test/cases/line-cont/README.md
Labels: testing

#685 Extract NFA.getDfa() to DfaFactory.createFromNfa()
  jflex/src/main/java/jflex/core/DFA.java
  jflex/src/main/java/jflex/core/DfaFactory.java
  jflex/src/main/java/jflex/core/NFA.java
  jflex/src/main/java/jflex/generator/LexGenerator.java
Labels: code health

#688 Update homepage README
  README.md
Labels: documentation

#693 Check %include files' modified times for rebuild too
  jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/ClassInfo.java
  jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/JFlexMojo.java
  jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/LexSimpleAnalyzerUtils.java
  jflex-maven-plugin/src/test/java/jflex/maven/plugin/jflex/LexSimpleAnalyzerUtilsTest.java
Labels: enhancement

#696 address more errorprone warnings
  jflex/src/main/java/jflex/core/AbstractLexScan.java
  jflex/src/main/java/jflex/core/EOFActions.java
  jflex/src/main/java/jflex/core/Macros.java
  jflex/src/main/java/jflex/core/NFA.java
  jflex/src/main/java/jflex/core/RegExps.java
  jflex/src/main/java/jflex/dfa/DFA.java
  jflex/src/main/java/jflex/gui/GridPanel.java
Labels: code health
