Repository jflex-de/jflex, pull requests merged in 2019-11, with the labels that each got.

#430 Restore ant test for examples/simple
  .travis.yml
  jflex/examples/README.md
  jflex/examples/simple/README.md
  jflex/examples/simple/build.xml
  jflex/examples/simple/ivy.xml
  jflex/examples/simple/src/test/java/YylexTest.java
  scripts/test-examples.sh
Labels: bug

#572 add factory class for Emitter
  jflex/src/main/java/jflex/generator/Emitter.java
  jflex/src/main/java/jflex/generator/Emitters.java
  jflex/src/main/java/jflex/generator/LexGenerator.java
Labels: enhancement

#587 Upgrade Jflex bazel_rules to v5
  WORKSPACE
Labels: security

#588 Introduce class ErrorMessages.ErrorMessage
  jflex/src/main/cup/LexParse.cup
  jflex/src/main/java/jflex/core/Out.java
  jflex/src/main/java/jflex/core/ScannerException.java
  jflex/src/main/java/jflex/core/Skeleton.java
  jflex/src/main/java/jflex/generator/LexGenerator.java
  jflex/src/main/java/jflex/l10n/ErrorMessages.java
Labels: code health

#590 Test Starlark format
  .cirrus.yml
  .travis.yml
  java/jflex/ucd_generator/scanner/BUILD
  java/jflex/ucd_generator/ucd/BUILD
  java/jflex/ucd_generator/util/BUILD
  javatests/jflex/ucd_generator/emitter/unicode_version/BUILD
  javatests/jflex/ucd_generator/util/BUILD
  scripts/run-tests.sh
  scripts/test-bzl-format.sh
  scripts/test-java-format.sh
  third_party/deps.bzl
  third_party/unicode/BUILD
  third_party/unicode/unicode.bzl
Labels: code health

#597 Tool to migrate testsuite test cases automatically
  java/README.md
  java/jflex/migration/BUILD
  java/jflex/migration/BUILD.vm
  java/jflex/migration/MigrationException.java
  java/jflex/migration/MigrationTemplateVars.java
  java/jflex/migration/Migrator.java
  java/jflex/migration/README.md
  java/jflex/migration/TestCase.java
  java/jflex/migration/TestCase.java.vm
  java/jflex/migration/TestSpecScanner.flex
  java/jflex/testing/testsuite/BUILD
  java/jflex/testing/testsuite/JFlexTestRunner.java
  java/jflex/testing/testsuite/golden/BUILD
  java/jflex/testing/testsuite/golden/GoldenInOutFilePair.java
  java/jflex/ucd_generator/BUILD
  java/jflex/ucd_generator/emitter/unicode_properties/BUILD
  java/jflex/ucd_generator/emitter/unicode_properties/UnicodePropertiesEmitter.java
  java/jflex/ucd_generator/emitter/unicode_version/BUILD
  java/jflex/ucd_generator/emitter/unicode_version/UnicodeVersionEmitter.java
  java/jflex/util/javac/BUILD
  java/jflex/util/javac/CompilerException.java
  java/jflex/util/javac/JavaPackageUtil.java
  java/jflex/util/javac/JavacUtil.java
  java/jflex/util/javac/README.md
  javatests/jflex/testcase/apipirivate/ApiPrivateTest.java
  javatests/jflex/testcase/apipirivate/BUILD
  javatests/jflex/testcase/caseless_jflex/BUILD
  javatests/jflex/testcase/caseless_jflex/CaselessGoldenTest.java
  javatests/jflex/testcase/caseless_jflex/caseless-0.input
  javatests/jflex/testcase/caseless_jflex/caseless-0.output
  javatests/jflex/testcase/caseless_jflex/caseless.flex
  javatests/jflex/testing/javac/BUILD
  javatests/jflex/ucd_generator/emitter/unicode_properties/BUILD
  javatests/jflex/util/javac/BUILD
  javatests/jflex/util/javac/JavaPackageUtilTest.java
  third_party/README.md
  third_party/com/google/code/README.md
  third_party/com/google/common/flogger/BUILD
  third_party/deps.bzl
  third_party/maven_install.json
Labels: enhancement

#595 Documentation on how to write integration test with Bazel
  README.md
  javatests/jflex/testcase/README.md
  testsuite/testcases/src/test/cases/README.md
Labels: documentation

#606 Update Changelog.md
  CODEOWNERS
  README.md
  jflex/changelog.md
Labels: documentation

#607 Do not run google-java-format on Unicode_x_y.java
  scripts/test-java-format.sh
Labels: code health

#604 Make zzScanError static
  jflex/src/main/java/jflex/generator/Emitter.java
Labels: code health

#608 Send code coverage reports
  .bazelrc
  .cirrus.yml
  pom.xml
  report-module/README.md
  report-module/pom.xml
  scripts/send-code-coverage.sh
Labels: code health, testing

#611 Remove unnecessary fully qualified names
  javatests/jflex/ucd_generator/ucd/UcdVersionsTest.java
  jflex/src/main/java/jflex/core/ScannerException.java
  jflex/src/main/java/jflex/generator/Emitter.java
Labels: code health

#605 Make `yychar` long
  docs/md/lex-specs.md
  docs/pt_BR/manual-pt_BR.tex
  javatests/jflex/testcase/large_input/BUILD
  javatests/jflex/testcase/large_input/LargeInputTest.java
  javatests/jflex/testcase/large_input/NegativeYyCharException.java
  javatests/jflex/testcase/large_input/RepeatContentReader.java
  javatests/jflex/testcase/large_input/large_input.flex
  jflex/changelog.md
  jflex/examples/simple/src/main/java/Yytoken.java
  jflex/src/main/jflex/skeleton.nested
  jflex/src/main/resources/jflex/skeleton.default
  testsuite/testcases/src/test/cases/simple/.gitignore
  testsuite/testcases/src/test/cases/simple/Utility.java
  testsuite/testcases/src/test/cases/simple/Yylex.java
  testsuite/testcases/src/test/cases/simple/Yytoken.java
  testsuite/testcases/src/test/cases/simple/simple-0.input
  testsuite/testcases/src/test/cases/simple/simple-0.output
  testsuite/testcases/src/test/cases/simple/simple-flex.output
  testsuite/testcases/src/test/cases/simple/simple.flex
  testsuite/testcases/src/test/cases/simple/simple.test
Labels: bug

#610 Bazelify testcase/count
  .bazelrc
  javatests/jflex/testcase/count/BUILD
  javatests/jflex/testcase/count/CountGoldenTest.java
  javatests/jflex/testcase/count/count-0.input
  javatests/jflex/testcase/count/count-0.output
  javatests/jflex/testcase/count/count.flex
  jflex/src/test/java/jflex/io/FileUtilTest.java
  testsuite/testcases/src/test/cases/count/README.md
Labels: testing

#619 Fix master build
  java/jflex/migration/Migrator.java
  javatests/jflex/testcase/count/CountGoldenTest.java
Labels: testing

#622 Disable error-prone FieldMissingNullable
  .bazelrc
Labels: code health

#609 Fix Error-prone: PrivateConstructorForUtilityClass
  cup-maven-plugin/src/main/java/jflex/maven/plugin/cup/JavaUtils.java
  java/jflex/migration/Migrator.java
  java/jflex/testing/testsuite/JFlexTestRunner.java
  java/jflex/ucd_generator/emitter/unicode_properties/UnicodePropertiesEmitter.java
  java/jflex/ucd_generator/emitter/unicode_version/UnicodeVersionEmitter.java
  java/jflex/util/javac/BUILD
  java/jflex/util/javac/JavaPackageUtils.java
  java/jflex/util/javac/JavacUtils.java
  javatests/jflex/testcase/apipirivate/ApiPrivateTest.java
  javatests/jflex/util/javac/BUILD
  javatests/jflex/util/javac/JavaPackageUtilsTest.java
  jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/JFlexMojo.java
  jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex/LexSimpleAnalyzerUtils.java
  jflex-maven-plugin/src/test/java/jflex/maven/plugin/jflex/LexSimpleAnalyzerUtilsTest.java
  jflex/pom.xml
  jflex/src/main/java/jflex/core/IntCharSet.java
  jflex/src/main/java/jflex/core/Out.java
  jflex/src/main/java/jflex/generator/Emitter.java
  jflex/src/main/java/jflex/io/FileUtils.java
  jflex/src/main/java/jflex/l10n/ErrorMessages.java
  jflex/src/test/java/jflex/core/SkeletonTest.java
  jflex/src/test/java/jflex/io/BUILD
  jflex/src/test/java/jflex/io/FileUtilsTest.java
  jflex/src/test/java/jflex/testing/TestFileUtils.java
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/ExecUtils.java
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/JFlexTestsuiteMojo.java
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/PomUtils.java
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/TestCase.java
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/TestsuiteUtils.java
Labels: code health

#625 Move the creation of the scanner in AbstractGoldenTest
  java/jflex/migration/TestCase.java.vm
  java/jflex/testing/testsuite/golden/AbstractGoldenTest.java
  javatests/jflex/testcase/caseless_jflex/CaselessGoldenTest.java
  javatests/jflex/testcase/caseless_jlex/CaselessGoldenTest.java
  javatests/jflex/testcase/count/CountGoldenTest.java
  javatests/jflex/testcase/ctorarg/CtorArgTest.java
  javatests/jflex/testcase/cupsym/CupsymGoldenTest.java
  javatests/jflex/testcase/dot_newline/DotnewlineGoldenTest.java
Labels: testing

#631 Bazelify testcase/ccl_pre
  javatests/jflex/testcase/README.md
  javatests/jflex/testcase/ccl_pre/BUILD
  javatests/jflex/testcase/ccl_pre/CclPreGoldenTest.java
  javatests/jflex/testcase/ccl_pre/ccl-0.input
  javatests/jflex/testcase/ccl_pre/ccl-0.output
  javatests/jflex/testcase/ccl_pre/ccl.flex
  testsuite/testcases/src/test/cases/ccl-pre/README.md
Labels: testing

#629 Improve performance of RepeatedContentReader
  javatests/jflex/testcase/large_input/LargeInputTest.java
  javatests/jflex/testcase/large_input/RepeatContentReader.java
Labels: testing

#628 Bazelify testcase/test-esc
  javatests/jflex/testcase/ccl_esc/BUILD
  javatests/jflex/testcase/ccl_esc/CclTest.java
  javatests/jflex/testcase/ccl_esc/Token.java
  javatests/jflex/testcase/ccl_esc/ccl.flex
  testsuite/testcases/src/test/cases/ccl-bug/README.md
  testsuite/testcases/src/test/cases/ccl-esc/README.md
Labels: testing

#633 Bazelify testcase/empty-match
  javatests/jflex/testcase/empty_match/BUILD
  javatests/jflex/testcase/empty_match/EmptymatchGoldenTest.java
  javatests/jflex/testcase/empty_match/emptymatch-0.input
  javatests/jflex/testcase/empty_match/emptymatch-0.output
  javatests/jflex/testcase/empty_match/emptymatch.flex
Labels: testing

#636 Bazelify testcase/eol-look
  javatests/jflex/testcase/eol_look/BUILD
  javatests/jflex/testcase/eol_look/EolGoldenTest.java
  javatests/jflex/testcase/eol_look/eol-0.input
  javatests/jflex/testcase/eol_look/eol-0.output
  javatests/jflex/testcase/eol_look/eol.flex
  testsuite/testcases/src/test/cases/eol-look/README.md
Labels: testing

#635 Bazelify testcase/eol-comment
  javatests/jflex/testcase/eol_comment/BUILD
  javatests/jflex/testcase/eol_comment/EolCommentTest.java
  javatests/jflex/testcase/eol_comment/eolcomment.flex
  testsuite/testcases/src/test/cases/eol-comment/README.md
Labels: testing

#637 Bazelify testcase/fixed look
  java/jflex/migration/Migrator.java
  javatests/jflex/testcase/fixed_look/BUILD
  javatests/jflex/testcase/fixed_look/FixedlookGoldenTest.java
  javatests/jflex/testcase/fixed_look/fixedlook-0.input
  javatests/jflex/testcase/fixed_look/fixedlook-0.output
  javatests/jflex/testcase/fixed_look/fixedlook-1.input
  javatests/jflex/testcase/fixed_look/fixedlook-1.output
  javatests/jflex/testcase/fixed_look/fixedlook-2.input
  javatests/jflex/testcase/fixed_look/fixedlook-2.output
  javatests/jflex/testcase/fixed_look/fixedlook-3.input
  javatests/jflex/testcase/fixed_look/fixedlook-3.output
  javatests/jflex/testcase/fixed_look/fixedlook.flex
  testsuite/testcases/src/test/cases/fixed-look/README.md
Labels: testing

#638 Bazelify testcase/buffer
  javatests/jflex/testcase/buffer/BUILD
  javatests/jflex/testcase/buffer/BufferTest.java
  javatests/jflex/testcase/buffer/buffer.flex
  testsuite/testcases/src/test/cases/buffer/README.md
Labels: testing

#639 Bazelify testcase/eof-min
  javatests/jflex/testcase/eof_min/BUILD
  javatests/jflex/testcase/eof_min/EofminGoldenTest.java
  javatests/jflex/testcase/eof_min/eofmin-0.input
  javatests/jflex/testcase/eof_min/eofmin-0.output
  javatests/jflex/testcase/eof_min/eofmin-1.input
  javatests/jflex/testcase/eof_min/eofmin-1.output
  javatests/jflex/testcase/eof_min/eofmin.flex
  testsuite/testcases/src/test/cases/eof-min/README.md
Labels: testing

#640 Bazelify testcase/generics
  java/jflex/migration/BUILD
  java/jflex/migration/BUILD-header.bzl
  java/jflex/migration/BUILD.vm
  java/jflex/migration/Migrator.java
  javatests/jflex/testcase/README.md
  javatests/jflex/testcase/generics/BUILD
  javatests/jflex/testcase/generics/Generics2GoldenTest.java
  javatests/jflex/testcase/generics/Generics3GoldenTest.java
  javatests/jflex/testcase/generics/Generics4GoldenTest.java
  javatests/jflex/testcase/generics/GenericsGoldenTest.java
  javatests/jflex/testcase/generics/generics.flex
  javatests/jflex/testcase/generics/generics2.flex
  javatests/jflex/testcase/generics/generics3.flex
  javatests/jflex/testcase/generics/generics4-0.input
  javatests/jflex/testcase/generics/generics4-0.output
  javatests/jflex/testcase/generics/generics4.flex
  testsuite/testcases/src/test/cases/generics/README.md
Labels: testing
