Repository jflex-de/jflex, pull requests merged in 2022-12, with the labels that each got.

#953 Property test improvement
  jflex/src/main/java/jflex/state/StateSet.java
  jflex/src/test/java/jflex/core/unicode/BUILD.bazel
  jflex/src/test/java/jflex/core/unicode/CharClassesQuickcheck.java
  jflex/src/test/java/jflex/core/unicode/IntCharGen.java
  jflex/src/test/java/jflex/core/unicode/IntCharSetGen.java
  jflex/src/test/java/jflex/state/BUILD.bazel
  jflex/src/test/java/jflex/state/OffsetGen.java
  jflex/src/test/java/jflex/state/StateSetGen.java
  jflex/src/test/java/jflex/state/StateSetQuickcheck.java
Labels: testing

#983 testsuite: remove invalid OrphanedFormatString warning
  java/de/jflex/testing/testsuite/JFlexTestRunner.java
Labels: code quality, testing

#984 testsuite: sync verbosity behaviour with main jflex
  java/de/jflex/testing/testsuite/JFlexTestRunner.java
  java/de/jflex/testing/testsuite/annotations/TestSpec.java
  jflex/src/main/java/jflex/core/AbstractLexScan.java
Labels: code quality
