Repository jflex-de/jflex, pull requests merged in 2023-01, with the labels that each got.

#988 github: update workflow action versions
  .github/workflows/build.yml
  .github/workflows/gjf.yml
Labels: code quality

#990 cup-maven-plugin test: replace createTempDir()
  cup-maven-plugin/src/test/java/jflex/maven/plugin/cup/GenerateMojoTest.java
Labels: code quality

#992 jflex UnicodeProperties: remove warning
  jflex/src/main/java/jflex/core/unicode/UnicodeProperties.java
Labels: code quality

#993 anttask: provide clone() implementation
  jflex/src/main/java/jflex/anttask/JFlexTask.java
Labels: code quality

#994 maven-testsuite: remove potential Null deref
  testsuite/jflex-testsuite-maven-plugin/src/main/java/jflex/maven/plugin/testsuite/DiffStream.java
Labels: code quality

#1006 README: spelling, markdown lint
  README.md
Labels: docs

#1007 README: use markdown image links
  README.md
Labels: docs

#1017 github: refine bazel cache management
  .github/workflows/build.yml
Labels: testing

#1018 github: document GH cache policy
  .github/workflows/build.yml
Labels: testing

#1019 jflex: make ErrorMessages a real enum
  jflex/src/main/cup/LexParse.cup
  jflex/src/main/java/jflex/l10n/ErrorMessages.java
  jflex/src/main/java/jflex/logging/Out.java
  jflex/src/main/java/jflex/scanner/ScannerException.java
Labels: code quality

#1022 jflex PackEmitter: remove debugging code
  jflex/src/main/java/jflex/generator/PackEmitter.java
Labels: bug

#1023 github: filter CodeQL results
  .github/workflows/codeql.yml
Labels: code quality

#1028 lib: syntax highlighting for new directives
  jflex/lib/jflex-mode.el
  jflex/lib/jflex.vim
Labels: enhancement

#1031 jflex emitter: prevent resource leak
  jflex/src/main/java/jflex/generator/Emitter.java
Labels: code quality

#765 Make maven build reproducible
  pom.xml
Labels: enhancement

#1033 dependencies: update guava to 31.1-jre
  pom.xml
  third_party/deps.bzl
  third_party/maven_install.json
Labels: dependencies

#1035 tests: warn/no-warn/suppress, fix %warn all
  javatests/de/jflex/testcase/no_warn/BUILD.bazel
  javatests/de/jflex/testcase/no_warn/NoWarnTest1.java
  javatests/de/jflex/testcase/no_warn/NoWarnTest2.java
  javatests/de/jflex/testcase/no_warn/NoWarnTest3.java
  javatests/de/jflex/testcase/no_warn/no_warn1.flex
  javatests/de/jflex/testcase/no_warn/no_warn1_sysout.txt
  javatests/de/jflex/testcase/no_warn/no_warn2.flex
  javatests/de/jflex/testcase/no_warn/no_warn2_sysout.txt
  javatests/de/jflex/testcase/no_warn/no_warn3.flex
  javatests/de/jflex/testcase/no_warn/no_warn3_sysout.txt
  jflex/src/main/java/jflex/core/OptionUtils.java
Labels: bug, testing

#1041 cup-maven-plugin: fix comment typos
  cup-maven-plugin/src/main/java/jflex/maven/plugin/cup/GenerateMojo.java
Labels: minor
